### PR TITLE
Update folders to equivalate 095e275

### PR DESCRIPTION
**Pull request by Fohlen**
Following PR brings back the Node.js support as it used to be before "the big"
Anyhow we will have to rethink about Node.js packaging since it relies on the `.proto` file and that one in turn is in the `build` folder using conan..

### CODE REVIEW

**Comment by Croydon** [comment]
Sorry for spam, this is a notifico test.

**Comment by Croydon** [comment]
Notifico test; PR comment

**Comment by Croydon** [comment]
> Following PR brings back the Node.js support as it used to be before "the big"

The big what?

**Comment by Fohlen** [comment]
The big PR with about 1000 files changed .. @a-teammate splitted it up and merged the C++ side respectively.

**Comment by a-teammate** [comment]
The .proto file gets installed in ./bin/ for all archs and os, so this is no problem.

I think the more pressing question we have now with this PR is:
How can we keep the code repo clean of binary blobs?
There are several images commited and I think this will pretty rapidly increase the repo size.
Can we put them somewhere in the media repos? or can we put the whole node folder to media?
Or should we make it a submodule?

**Comment by aschaeffer** [comment]
:+1: for separate nodejs stuff from c++ stuff --> #360

Because _Inexor Flex_ will start _Inexor Kernel_ in future, we should reverse the submodule: _Inexor Flex_ has a submodule _Inexor Kernel_.

**Comment by a-teammate** [comment]
So is this one obsolete?

**Comment by Fohlen** [comment]
I think so

**Comment by aschaeffer** [comment]
Yes

**Pull request closed without merging**
