### PR TITLE
Fohlen/fixcef

### LINKED ISSUE #177: Fix double input while running CEF
When running CEF, at least in wine, the normal console receives each character twice.
This is caused by SDL_ providing two SDL_TEXT events but not more than usual SDL_KEYUP/DOWN events.

Please check whether this problem also occurs on windows.

### PR DESCRIPTION
**Pull request by Fohlen**
This basically includes a fix for the current CEF implementation (single browser process).
As @koraa  and @aschaeffer and me are working on a separate process mode, this is only a rudimentary, temporary fix.

Since (A LOT) happened while we worked on this branch, the sole interesting commits to cherry-pick are those between ff95143 to b77d8f0

The submodule structure has been fixed and enhanced by @koraa, so using the beyond approach is as well *only* a temporary fix (using argc and argv in a separate method).

The following PR fixes #177. @koraa already did a PR (276) but it comes with 0 files and 0 lines, so I was uncertain and resubmitted this PR. Can be either merged or closed, @koraa ?

### CODE REVIEW

**Comment by koraa** [comment]
I think it might be a more viable approach to base any further CEF process work on f49b81be64f87c27b9e465fe9b5aeedbe0924f3b and use separate executables.
It basically works, there are still bugs but I saw the same bugs without the separate executables. (Input problems, ...)

**Comment by Fohlen** [comment]
As far as I am concerned the double input originates from 2 continuously running main-loops.
This issue is concerned within the PR.
Anyhow I agree on focusing any further effort on karo+fohlen+hanack/fix_cef

**Comment by koraa** [comment]
Ok, in this case, using a separate main function would implicitly fix this problem.

**Comment by Fohlen** [comment]
What's the status of this? Merge or close?

**Comment by koraa** [comment]
close

**Pull request closed without merging**
