### PR TITLE
New windows batches

### PR DESCRIPTION
**Pull request by Efreak**
Fixes for the batch files. First it didn't work because bad syntax, then it didn't work because different folders.

### CODE REVIEW

**Comment by Fohlen** [comment]
:+1: 
Very much appreciated.
@a-teammate or @Croydon could you verify this patch is actually working?

**Comment by koraa** [comment]
+++1 thanks!

**Comment by Croydon** [comment]
Thanks for contributing, however this pull request doesn't work.

The $HOME variable isn't wrong, it gets replaced with the Windows constant "CSIDL_PERSONAL" (https://msdn.microsoft.com/en-us/library/windows/desktop/bb762494%28v=vs.85%29.aspx) by the function "subhomedir" (https://github.com/inexor-game/code/blob/a5fb9d78b4b5d326ac69018e10548ab1a263a98e/src/shared/stream.cpp#L384). So multiuser setups should work fine.

Moreover your version is expecting, that the directory is already existing. But that isn't required, since a new directory can created everywhere by the .exe.

To set a different home directory, one could simple run:
> start bin\windows\%INEXOR_ARCH%\inexor.exe "-qC:\newhomedir"

However, I see the point, that this is perhaps not the perfect solution, since the path to the .exe and the other parameters would also need to get set manually. Could you please check the following and tell me if this would be a solution for your user case? https://gist.github.com/Croydon/01d5d0f93ef52a937508
Could you also explain why you used "SETLOCAL ENABLEEXTENSIONS"?

**Comment by Efreak** [comment]
My intention was the data. I assumed that this directory was the only place the game looks for the contents of data repository, It didn't occur to me to try adding another -q parameter.

**Pull request closed without merging**
