### PR TITLE
Make CEF the primary user interface [PRIORITY/IN-PROGRESS]

### PR DESCRIPTION
**Pull request by Fohlen**
The goal is to switch the user interface from cubescript+g3d to CEF+HTML5+CSS+JavaScript.
- [x] [~~Upgrade CEF to 'branch 2526' (therefore requires plattform repository 'branch 2526')~~](https://github.com/inexor-game/platform/pull/6)
- [x] [~~Upgrade CEF to 'branch 2704' (therefore requires plattform repository 'branch 2704')~~](https://github.com/inexor-game/platform/pull/6)
- [ ] Stable initialization of CEF
- [ ] Stable shutdown of CEF
- [x] ~~CEF rendering in a separate subprocess~~
- [ ] autodetect the subprocess binary
- [x] Resizing the (CEF) user interface layer (fullscreen / screen resolution changes)
- [x] Synchronizing the Inexor Tree from Inexor (CPP) via protobuf-IPC to Inexor (NodeJS)
- [x] REST API from Inexor (NodeJS) for the user interface
- [ ] User interface component / service for accessing the Inexor Tree via REST
- [ ] SDL2 input (= key and mouse) event propagation from Inexor (CPP) to CEF
- [ ] User interface state (menu und hud states) propagation from Inexor (CPP) via CEF-IPC to the  HTML5+JavaScript user interface
- [ ] Rendering of the mouse cursor + resize the mouse resolution
- [ ] Responsive user interface as a single page application
- [ ] Main menu background -> HTML5
- [ ] Menu framework / CEF Layer for Menus and Webapplications
- [ ] Loading menu definitions from JSON files / Define menus in the Inexor Tree
- [ ] HUD framework / CEF Layer for HUDs
- [ ] Loading HUD definitions from JSON files / Define HUDs in the Inexor Tree
- [ ] First set of default menus: main menu, multiplayer, options, ...
- [ ] GameStateHUD
- [ ] ScoreBoardHUD
- [ ] Console WebApp
- [ ] Remove cubescript console rendering
- [x] Remove g3d menu rendering
- [x] Remove g3d cursor rendering

This is a rebase/fork of `karo+fohlen+hanck/fix_cef` against the current master. Consider closing it.
Please consider that we're only getting at the final stage, and there is still broken stuff that we will fix in the upcoming weeks!:)

### CODE REVIEW

**Comment by Croydon** [comment]
Why is upgrading CEF to 2526 striked through?

**Comment by aschaeffer** [comment]
Because it's done?

**Comment by Croydon** [comment]
@aschaeffer It is not merged nor tested?

**Comment by a-teammate** [comment]
Closed in favor of #350

**Pull request closed without merging**
