### PR TITLE
Some README suggestions

### PR DESCRIPTION
**Pull request by PowerKiller**
Fixes: 1) Should be in capitals
2) Updated goals Lol xD

### CODE REVIEW

**Comment by PowerKiller** [comment]
Now, you can merge this. I have finished up setting Documentation.

**Comment by a-teammate** [comment]
The links section is a good start :)
We'll the point of improving the readme should be to actually tell something about ourselves (this point is actually already pretty good summarized in our old readme, so its okay to copy that part) and our goals and our methods (therefore the "design-decisions" posts should be shrinked imo),
maybe even a little really shortened instruction guide to build that stuff and to dive into the project.

We then could/should still tell something like "look at the wiki for further instructions" in the specific parts, but the point should be to get rid of the straight pointing to our wiki and provide some useful info directly in the readme.
Currently, its only about sauerbraten engine features (those can stay in, but do not need to). and btw they shouldnt be marked as our own goals or achievements ^^.
and yes: i would still advise you to work on that on a pad, since more people can work on that directly there and edit parts faster (it still has a timeline with all the edits btw)

**Comment by PowerKiller** [comment]
OK.

**Comment by koraa** [comment]
++1 to what a teammate said. Though I'd like to see at least a few of the inexor features in there.

Could you also please rebase to create sensible, atomic, commit messages? Otherwise I think this can be merged :)

**Comment by PowerKiller** [comment]
Sensible, Atomic, Do I need to put something like this "PowerKiller commited "Dropped bomb on Hiroshima", "Dropped bomb on  Nagasaki" ?

**Comment by koraa** [comment]
Use the rebase method:

Sensible means "with a decent meaning".
Atomic means: Smallest logical changesets possible, but not one changeset distributed among two commits".

If you have a  commit updating the readme an then one fixing typos, you've split the atom (boom, this is my git sence of decency exploding :P)
If you commit "Updated readme and improve graphics"  you've built a molecule. Maybe it's Sarin. *hiss*

https://gist.github.com/tmcgilchrist/1785908
http://www.randyfay.com/node/91
http://www.randyfay.com/node/89

**Comment by PowerKiller** [comment]
lolwut?

**Pull request closed without merging**
