### PR TITLE
appveyor: speedup

### PR DESCRIPTION
**Pull request by a-teammate**
by skipping to build pull requests and by caching files across builds

### CODE REVIEW

**Comment by Croydon** [comment]
Can you configure the caching on the appveyor Website?

**Comment by a-teammate** [comment]
I'd like to merge this pr today eve.

@Croydon: I removed caching from this PR since appveyor has a limit of 500MB on the cache and the dirty tricks (removing parts of the platform repo + a lot of cmd fucks) i needed to do to achieve this didnt really overweight the speedup of the build imo (~2 minutes).

**Comment by Fohlen** [comment]
Most notably is that appveyor apparently has a poor instance architecture, which is why it takes so long until a worker actually gets assigned to build a job. disabling the debug configuration, which we don't use / upload at the moment, is very important to speed up the builds (which is ridicilious, hmm). :+1: for merging!
If @bebehei manages to set up a Jenkins on his resources we might use mingw to actually cross-compile

**Comment by a-teammate** [comment]
merged with 9e6f19cab0b5216d1139466f1463ad19d2575d25

**Pull request closed without merging**
