### PR TITLE
a_teammate/updates

### PR DESCRIPTION
**Pull request by a-teammate**
This pull request basicly merges the commits sauerbraten has made since our last sync.
Those commits have been reviewed to a high extent.

Moreover it fixes some other stuff, like **the hud** (we temporarily disabled) and cleans up some random stuff which cried for refractoring.

it also only works together with __data/a_teammate/updates__ so you'll have to use that specific data repository to give this PR a try.

(Consequently it also "fixes" the #151 by adding the missing files)

from sauerbraten the following changes have been made:

#### remove all but the shader rendering..
Although i understand it may infect performance and i wished we wouldnt drop that support for it i figure that the point is not to have a fallback rendering pipeline for me, but to have the possibility to improve performance withhin a few settings.
Therefore, instead of leaving a lot of fixed-function stuff inside we should merge it out now and instead give a feature, cutting stuff out in the shaderpipeline to improve fps. ive got some ideas in mind for that but that has to wait probably.

the changes are however in combination with a lot of cleanups so you should avoid the fixed function stuff from here on (or adapt it later). This is means not using e.g.
glColor3f or glBegin(..) stuff anymore. (use gle:: blablablub instead)
Why? because then well be able to do update our driver profile (especially on mac) which could/will result in better performance.

#### remove nompedit
#114 

 +
some nasty 'cleanups' for sauerbraten uniques like hashsets, formatstring, matrixes and vectors im not entirely confirm with, but for one big reason its still worth to update those:

#### adapt the old uniques to tesseract

our codebase will be *a lot* more similar to tesseract ones than before, making diffs and seeing changes much easier.

### CODE REVIEW

**Comment by Fohlen** [comment]
Have you fixed the network version (which was 259) and the server port (which has been reseted to 28785) as well?

**Comment by a-teammate** [comment]
nope, that is going to change when i rebase to master.

**Comment by Fohlen** [comment]
:+1:

**Comment by a-teammate** [comment]
merged in addition with a new cubescript command to retreive the current time "gettimestr formatstr"
and with a new screenshot formatting

**Pull request closed without merging**
