### PR TITLE
Fix key being printed in chat

### LINKED ISSUE #279: Pressing the button to open the chat-console also prints the key in the chat-console (saycommand)
How to reproduce:

- Launch inexor (default configuration)
- hit t to open the chat-console

The chat-console opens and a "t" appears in the chat-console which should not be there.
This happens only once. After you opened the chat one time it works fine.

OS: Ubuntu 14.04.3
master branch rev 7650f294c252b97eafbcab76460d8aadd0a3385d

### PR DESCRIPTION
**Pull request by DarkDeepBlue**
Fixes #279

### CODE REVIEW

**Comment by a-teammate** [comment]
+1

**Comment by a-teammate** [comment]
tested and works

**Comment by Fohlen** [comment]
:+1:

**Comment by Croydon** [comment]
Thanks.

**Pull request merged**
