### PR TITLE
C++14 Linux CI (and further cleanups)

### PR DESCRIPTION
**Pull request by koraa**
Enable the CI to compile using the modern C++14 standard.

### CODE REVIEW

**Comment by koraa** [comment]
I am looking at the platform code again, and it's still a bit confusing.

What do you think about the following variables:
```
# These identify what the host system is running
HOST_LINUX
HOST_OSX
HOST_POSIX
HOST_WINDOWS

# These identify what the destination system is running
DEST_MINGW
DEST_LINUX
DEST_OSX
DEST_WINDOWS
DEST_POSIX

# These identify what compiler is used
COMPILER_GCC
COMPILER_CLANG
COMPILER_VS
```

This seems a bit more sane than the current setup, where we don't really distinguish between the target OS, the source OS and the compiler.

**Comment by Croydon** [comment]
There is the variable CMAKE_COMPILER_IS_GNUCXX. No idea why such a thing doesn't exists for other compilers.

**Comment by Croydon** [comment]
We have an own issue for that btw #169

**Comment by koraa** [comment]
Seems to work. Errors are because the nightly build server is running full.
WIll be merged this night if all CIs are working.

**Pull request merged**
