### PR TITLE
a_teammate/ao_fix

### PR DESCRIPTION
**Pull request by a-teammate**
i'll merge that 2 master soon as well (today or if someone vetos tomorrow the latest)

its basicly just a fix (a crash caused when calclighting) + making ambient occlusion shadows antialiased

### CODE REVIEW

**Comment by a-teammate** [comment]
merge tmrw, no further changes planned

**Comment by koraa** [comment]
Plase squash your fix commits

**Comment by koraa** [comment]
Please also rebase your commits onto the latest master

**Comment by a-teammate** [comment]
merged

**Pull request closed without merging**
