### PR TITLE
Inexor IPC + Node IPC Client

### PR DESCRIPTION
**Pull request by koraa**
Implementation of a very basic IPC method for Inexor.

Ultimately this should provide a method of sending CRUD commands to the Inexor process,
thereby making it possible to outsource most of the business logic to a high-level language,
while keeping the performance critical and graphic rendering stuff inside the C++ Inexor process.

This issue is particularly dear to me, since it could reduce to difficulty for beginners a lot.

This pull request also includes a reference implementation of a Node.js client.

### Current Status

The current status of the IPC implementation is very basic, but it works:
The communication between Client and Server works, there is some basic tests and it is documented to a large degree.

At the moment one RPC instruction is implemented, which lets a client execute arbitrary cubescript code on the server.

The purpose of this pull request is to kick of a public beta for this:
The basic architecture of Inexor has not been changed; using the IPC subsystem is completely opt in at the moment.

As the IPC system is always being compiled into the Inexor binary, protobuf and boost/asio is, beginning with this branch, a hard requirement for compiling Inexor.
Node.js is only required is one want's to test the reference client.

### Tech

The Inexor IPC protocol implements an RPC interface using google Protocol buffers to encode remote call instructions and to encode Function arguments and return values.
This utilizes a reliable, connection oriented transport that preserves message boundaries. At the moment we're either using stream oriented unix sockets or tcp and cut the streams manually.
TCP and Unix Sockets abstractions are provided by ASIO.

# Getting it to run

## Dependencies

To compile you will need:
* asio
* google protocol bufferts

To run the IPC client, you will need node.js (neither compiling nor running reqires node.js).

### Clang

Compiling with clang is a bit special (see http://think-async.com/Asio/AsioStandalone).
Hence Boost::system is required to compile, though it appears only the headers are necessary (but don't bet on this :) ).

### *nix

1. Compile Inexor
2. Run Inexor (and keep it running): $ inexor_unix
3. Execute in inexor: `initrpc`
4. Run the client: $ inexor_cipc_unix # A shell should open, INEXOR must be running for this!
  1. > Inexor = require 'inexor'
  2. > Inexor.eval "echo hallo123", (x) -> console.log x

You should now have a text "hallo123" in the console of inexor.

### Windows

1. Compile Inexor
2. Run Inexor (and keep it running)
3. Execute in inexor: `initrpc`
4. CD into the node directory
5. Update the node packages: $ npm update
6. Run the client: $ NODE_PATH=. node node_modules/.bin/coffee # A shell should open, INEXOR must be running for this!
  1. > Inexor = require 'inexor'
  2. > Inexor.eval "echo hallo123", (x) -> console.log x

You should now have a text "hallo123" in the console of Inexor.

## Windows Support

I tried to keep windows support, but I assume that some things will break, because I was unable to test those.

* I think c++11 support is enabled by default since msvc2010, but I am not sure of that
* The protocol file `src/rpc/inexor_service.proto` gets compiled to c++ files during compilation. This might break because protobuf is not in the default path or because I did not write the executable with ".exe"

On Unix we use unix sockets for IPC; they are very quick and they provide file based permission.
On windows we use tcp sockets (maybe even on public interfaces). We should provide something better than that.

## OSX Support

Should work out of the box; Mac is UNIX compliant.

## Further Direction

I am planning to add a few more basic features to the IPC interface:
* Event handling
* Locking (for sending a lot of commands to sauer consecutively)
* A remote object interface for things like the ents/players/...
* Method based cubescript interface (calling Inexor.cube.echo instead of Inexor.eval "echo ...")
* Improved IPC transports (e.g. shared memory queue + signals)

# PLEASE TEST :)

### CODE REVIEW

**Comment by koraa** [comment]
@killme Could you check about the travis build? I just tried to add the libs to the debian install, but it did not work and I am not sure how to debug this.

**Comment by koraa** [comment]
Could someone please try to get this running on windows?

**Comment by a-teammate** [comment]
I already test them, though they will need a lot of dependencies in platform_windows,
maybe you could in the maintime try to get rid of boost? :)

**Comment by koraa** [comment]
@a-teammate: The Platform-Windows repository and the CMakeLists will require updating in any case. Could you try doing that for win?

**Comment by koraa** [comment]
@a-teammate I don't havve time to do any coding during the next couple of days. If you feel getting rid of the boost dependency is necessary to get this run on windows, please feel free to do so and push onto this pull request.

**Comment by Croydon** [comment]
At least I feel better now after I got stuck at the same point @a-teammate :D

**Comment by koraa** [comment]
The branch is now building fine with mingw and on linux and I was able to verify that the mingw build runs with wine.
It might be still good to verify whether the binaries run on windows, so it would be cool if someone could run [these](https://cupdev.net/~karo/tmp/bin_win64.zip) on windows.

Since it appears to be working quite fine I'll be merging in a couple of hours.

**Comment by aschaeffer** [comment]
+1

**Pull request merged**
