### PR TITLE
console autocomplete shift-tab to go backwards

### PR DESCRIPTION
**Pull request by basile-henry**
Tiny feature! Adding the possibility to TAB complete backwards by pressing SHIFT at the same time.

When you go through all the possible commands using TAB and you miss the one you want because you pressed TAB again and can't be bothered to actually type it out SHIFT-TAB comes to the rescue.

### CODE REVIEW

**Comment by koraa** [comment]
I've sent you an invitation for the developer inexor group, so you can merge yourself.

Please always wait for confirmation that it works on win (I assume you're on linux) and always rebase!

The PR is great :D

**Comment by basile-henry** [comment]
I built and tested this feature in Windows 8.1 64bit. I'm merging the pull request!

**Comment by koraa** [comment]
Please don't produce any merge commits. Just rebase and merge on the command line.

**Comment by basile-henry** [comment]
Noted, I will do that for future pull requests. :)

**Pull request merged**
