### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by PowerKiller**
It has a typo.. I fixed that typo (get's should be gets)

### CODE REVIEW

**Comment by Fohlen** [comment]
I am sorry to report to you that we are dropping support for travis and are therefore not interested in cosmetic changes to this script.

**Comment by PowerKiller** [comment]
Okay...

**Comment by Croydon** [comment]
Veto, Travis makes it possible to [test on OS X](http://docs.travis-ci.com/user/osx-ci-environment/). We should expend it instead of drop it.
I would also like to have cross-compiling (Linux->Windows) tests back. Why was it dropped? When I'm not wrong I read something of "too old compiler"? However, [Travis is supporting GCC5]( https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L864).

**Comment by Fohlen** [comment]
@Croydon it was been dropped because of #23 which will allow us to compile distro-specific packages without hassle. Furthermore we use cloudbees.com at the moment, which also offers OSX dropplets.

**Comment by koraa** [comment]
Ditto. Thanks for the contribution @PowerKiller. There's no need to reject improvements to something that's not yet been phased out! (Also it's probably my grammar error).

As for Travis: Travis is being dropped because it made huge problems. Compiler bugs specifically. Everything we can do with travis we can do with our own CI too.

**Comment by PowerKiller** [comment]
lmao, remove the wontfix label. :-1:

**Pull request merged**
