### PR TITLE
Add RPM buildfiles. (Merge-able)

### PR DESCRIPTION
**Pull request by PowerKiller**
I'll also make DEB buildfiles later.

### CODE REVIEW

**Comment by Croydon** [comment]
Do we really need that in our core repository?

**Comment by aschaeffer** [comment]
yes, building (cmake) and packaging is part of the project

Am 27.02.2016 um 12:58 schrieb Michael Keck:

**Comment by bebehei** [comment]
@Croydon @aschaeffer no, not really. But I wanted to get the buildscripts from @PowerKiller

**Comment by PowerKiller** [comment]
why not keep it here?

**Comment by PowerKiller** [comment]
Is it merge-able?

**Comment by Croydon** [comment]
@aschaeffer Building is one thing, but packaging is a completely different story. And everything for Inexor is part of the project, but not everything is in the code repo :) 

@bebehei Created an extra repository for that, so I guess we can close this PR.

**Comment by PowerKiller** [comment]
Hmm, wait.
I can't seem to find the place to make another PR for including these.
Link me to it....
And yes in a way, you are right
When they are downloading code they shouldn't be downloading RPM buildscripts
By they I mean the users

**Comment by aschaeffer** [comment]
I think the code repo is the right place for the packaging scripts as well.
1. We wanted to make things less complicated.
2. In most other open source projects the packaging scripts are included in the source code repos
3. The an extra packaging repo would be only useful with the code repo. You can't reuse the packaging repo for anything else - so it's not independent
4. Usually the users are downloading ready packages for their OS/distribution - not the source code.

**Comment by a-teammate** [comment]
I dont see why this shouldnt be placed in the code repo either.

However @PowerKiller is it possible to remove the duplication of the changelog file and this spec-file? e.g. by reading the contents of the changelog.md directly in. (+ besides that we should probably do sth about the versioning, stating the version and name in every sourcefile seems a bit redundant. but thats probably out of the scope of this pr. However: are u sure "Release" needs to be set to 1? id define ourselves as prerelease actually, dunno whether thats the meaning of that tag though )

Furthermore: are u sure this works on an fresh box? i mean e.g. enet is missing, just noting, ive no machine to test that.

Otherwise nice to have :)

**Comment by Croydon** [comment]
I personally don't see how things should be getting more complicated with that. And what @PowerKiller likely meant was that the average developer doesn't care about packaging. Either you install existing ones or you compile the project on your own anyway.

We want to get rid of the platform repo, for instance, because it is nonsense to have Linux/Windows only stuff on the respective other platform. Now we are creating a similar situation here. Thinking a few steps ahead we would have here package stuff for the most important Linux package formats, a Windows installer and OSX stuff (however it is getting done there). 

But seems like I'm clearly outvoted. So go with it if you want. Since @bebehei seems to do the most work with packaging (correct me if I'm wrong) maybe he should have the last word here.

If this PR is getting to get merged the commits should definitely getting squashed.

**Comment by PowerKiller** [comment]
@a-teammate We need to specify it in every release, but I doubt if it can be omitted.
And also, it should work because it's using the same name that OBS uses.
@Croydon No wait, I meant this repo should only cointain source and only source, no other stuff like tools, RPM buildscripts, SPEC files, are useless to be here. I think you should keep that modular and clean/neat as possible.

**Comment by PowerKiller** [comment]
InstallerSheild ? :dart:

**Pull request closed without merging**
