### PR TITLE
TreeAPI make classes syncable

### PR DESCRIPTION
**Pull request by a-teammate**
Improve the gluegenerator in order to sync class singletons

TODO:

- ~~parse nested classes correctly~~ [DEFFERED]
- [x] make rpc run first on startup
  - add InexorTreeFullyInitialized event and wait for it
- [x] add lists
- [x] add functions
- [x] bump gluegen version

### CODE REVIEW

**Comment by a-teammate** [comment]
This can be merged. Today evening?

**Comment by Fohlen** [comment]
👍

**Comment by a-teammate** [comment]
Hm the tests are failing bc of some rights problem of the ui-console-submodule.
could you look into this and maybe improve the structure in a way we do not have a folder called "interface", next to one named "interfaces"? :D

**Comment by aschaeffer** [comment]
I didn't move the `interface` into `interfaces`. `interface` contains one interface, but I'd like to have an `interfaces` folder which can contain multiple interface folders: HUD (lightweight), Menu (lightweight), Console (lightweight) and Web-UI (the `interface` repo; containing more complex things like server browser, texture browser and so on).

**Comment by a-teammate** [comment]
hm ok, so the failing appveyor and jenkins builds are something else now.

I think i can fix the appveyor one, dunno about jenkins.

**Comment by a-teammate** [comment]
kk i'll fix VARN_NOSYNC shortly (its as simple as switching the SharedVar<int> back to an int :) )

**Comment by a-teammate** [comment]
The last commit is untested though, since I'm on the laptop currently

**Comment by aschaeffer** [comment]
Thx, it seems the VARN_NOSYNC is working again.

**Pull request merged**
