### PR TITLE
Integrate the muparser library

### PR DESCRIPTION
**Pull request by aschaeffer**
The muparser library parses mathematical expressions (from a string). It is fast and easy and transforms an expression into bytecode and precalculates constant parts of the expression. The library was designed with portability in mind and should compile on every standard compliant C++ compiler.

The requirement is to parse mathematical expressions with high performance and use it in the particle system. For example the vector field modifier is able to simulate gravity, rotation, turbulence, and so on by using mathematical expressions for modifying the velocity of a particle. By using dynamic expressions it makes the vector field modifier a lot more dynamic at runtime and avoids code duplication.

http://muparser.beltoforion.de/index.html

### CODE REVIEW

**Comment by a-teammate** [comment]
maybe you could add a readme to the folder the mu lib is provided, but otherwise it looks cool :)

**Comment by koraa** [comment]
I think integrating muparser is great, though I am not feeling one hundred percent confident that storing it in our own source tree.
Is there any way we can maintain this as an external dependency?

**Comment by Fohlen** [comment]
git submodule add http://muparser.googlecode.com/svn/trunk/

**Comment by koraa** [comment]
@Fohlen: Its a SVN repo

**Comment by aschaeffer** [comment]
It's not just adding it as a git module. You need to add it to the build system, too. You can easily import a project from SVN using the github svn importer. In this case it was possible, but in some cases there are a lot of binary files included which increases the file size of the submodule dramatically... for nothing.

**Comment by Fohlen** [comment]
On 24.01.2015 12:47, Andreas Schaeffer wrote:
>
> It's not just adding it as a git module. You need to add it to the
> build system, too. You can easily import a project from SVN using the
> github svn importer. In this case it was possible, but in some cases
> there are a lot of binary files included which increases the file size
> of the submodule dramatically... for nothing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inexor-game/code/pull/86#issuecomment-71313086>.
>
Agreed

**Comment by aschaeffer** [comment]
@a-teammate the readme is included in the repository, too

**Pull request closed without merging**
