### PR TITLE
WIP: snapcraft

### PR DESCRIPTION
**Pull request by Fohlen**
The following PR add's a WIP [snappy package](https://snapcraft.io/) for Inexor.
It is WIP because there's still some issues with the paths which I am hopefully able to resolve soon.
Despites, I did wanted to dig into the launchpad pipeline .. our snappy [packages are there too](https://code.launchpad.net/~inexor/+snap/inexor)!

### CODE REVIEW

**Comment by Fohlen** [comment]
@Croydon this could as well be builded by our Jenkins CI.

**Comment by Fohlen** [comment]
Once the `bash` script is adjusted we could as well change the package `grade` and add this to the `snapcraft store`.

**Comment by Fohlen** [comment]
The current `snapcraft.yaml` is struggeling with https://bugs.launchpad.net/ubuntu/+source/snapcraft/+bug/1576282

**Comment by Croydon** [comment]
@Fohlen I'm still struggeling with depedencies in our CI, when I'm done with that I want to look into the upload of Conan packages to conan.io (I expect a dramatically reduce in build time) and then I might look into building snap in our CI if you want.

Could we make snap a subdirectory of tool or something? I don't like it that we continue to add many directories in root.

**Comment by Fohlen** [comment]
@Croydon I did remove the folder.

**Comment by Croydon** [comment]
Oops. Sorry 😊

**Comment by elopio** [comment]
@Fohlen it would be useful if you comment on those bugs affecting you, with an explanation of your use case.

**Comment by Fohlen** [comment]
@elopio the issue is actually being caused because `python` is used in a `scriptlet`. That in turn falls back to system python, and all the "wooble" apparently caused issues with imports.

**Comment by elopio** [comment]
Interesting. I wonder if you could use something like $PYTHONPATH=$SNAPCRAFT_STAGE/... in the scriptlet.

**Comment by Fohlen** [comment]
Will be closed in favor of https://github.com/inexor-game/code/wiki/Release-and-build-strategy
Packages are:

- compiled on Travis
- pre-bundled via conan/virtualenv
- delivered via npm packages

**Pull request closed without merging**
