### PR TITLE
Add a minimal doxygen config

### PR DESCRIPTION
**Pull request by koraa**
Create a minimal doxygen config.

Install doxygen, run ` $ doxygen doxygen.conf`, enjoy doc/html/index.html`

And here is what it looks like: http://cupdev.net/~karo/tmp/inexor-doc/

### CODE REVIEW

**Comment by Zebrazilla** [comment]
+1

**Comment by a-teammate** [comment]
It neither finds hannis nor my comments so far :/

**Comment by aschaeffer** [comment]
You have to use a specific documenting style, described here:

http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html

I would suggest to use the widely used "Javadoc" style.

  /**
   * ... text ...
   */

A good manual about javadoc and code commenting in general can be found here:

http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html

**Comment by a-teammate** [comment]
using the javadoc style in comments all over the code makes the code:

* unreadable
* not easily block commentable
   * sometimes i want to comment out some parts of the code by using /* and */ 
   *  ifdef 0 is just a workaround

if you are writing a lib .. javadoc style could be ok as well, but for our purpose it should (at least) recognize both.

**Comment by aschaeffer** [comment]
Normally you comment classes, members and methods. Doxygen will produce an API documentation from the code. You have to stick on formating rules in order to enable the automatic parsing which is done by a tool.

You can comment out code with //-Blocks (every code line is prepended with //). Your favorite IDE brings support for toggling comment blocks (for example in eclipse "Toggle comment"). It's easy to detect what is an APIDOC and what uncommented code.

```
/**
 * This describes what the class is for.
 */
class SomethingImportant
{

    /**
     * This describes the member variable.
     */
    int member;

    /*
     * This describes the method DoSomethingImportant.
     * @param var1 This describes the var1.
     * @param var2 This describes the var2.
     */
    void DoSomethingImportant(int var1, int var2)
    {
        // Comment something (will not appear in the APIDOC)
        statement1();
        statement2();
    }

//    /*
//     * This describes the method DoSomethingLessImportant.
//     * @param var1 This describes the var1.
//     * @param var2 This describes the var2.
//     */
//    void DoSomethingLessImportant(int var1, int var2)
//    {
//        // Comment something (will not appear in the APIDOC)
//        statement1();
//        statement2();
//    }

}
```

**Comment by koraa** [comment]
@a-teammate We could also use ///, though I prefer javadoc style.

**Comment by a-teammate** [comment]
You are right, most IDE's support commenting stuff with single lines.
On the other hand do we develop for specific IDE's only or should other devs be independend of additional tools?

Personally I use the "comment out" function just for small pieces of code (100 lines max), and go for /* */ otherwise

**Pull request merged**
