### PR TITLE
Resolving issue #389

### PR DESCRIPTION
**Pull request by fallinbryan**
Every Header now has #pragma once, including the ones that had no include guards previously.

I am not sure how to squash all commits into one however.

### CODE REVIEW

**Comment by a-teammate** [comment]
Hey Bryan, Its already merged in #390 :)

**Comment by fallinbryan** [comment]
What about the header files that had no include guards at all?

**Comment by a-teammate** [comment]
Yeah i only did what i mentioned in the other PR: I did a simple find&replace for your comment and replaced them with include guards.

I just realized that ive "stolen" your PR maybe a bit, as you would have been able to learn to squash commits..
I'll try to open some more refactoring issues, which should be resolvable similarly.

How has your experience been [building](https://github.com/inexor-game/code/wiki/Build) Inexor? Did it work?
My suggestion is for squashing commits and anything git-related: Smartgit (you can do anything like that in the GUI)

**Comment by a-teammate** [comment]
Ah i see i missed some.. ups

**Comment by fallinbryan** [comment]
Yeah, there was just a few that I didn't 'git' commented. (apologies for the pun).   No worries about "stolen PR," I think it super cool I was able to contribute at all, as this was my first taste of social programming. 

I have not yet had to opportunity to try to build, finals week and all, but I hope to soon.  

I have been using the github desktop app, I will try  Smartgit though.

**Comment by IceflowRE** [comment]
Take a look at [Gitkraken](https://www.gitkraken.com/) too.

**Pull request closed without merging**
