### PR TITLE
Show error message instead of ASSERT when a vslot has an invalid texture definition as reported in #74.

### PR DESCRIPTION
**Pull request by killme**

### CODE REVIEW

**Comment by Croydon** [comment]
This prevents a crash, however, I get errors about textures who are existing, try out the map pandora for instance.

**Comment by Croydon** [comment]
I'm not 100% sure if this is related to this commit or if I have build it somehow different which causes that bug, but on explosions the whole map is getting darker till you move away far enough from the point of impact, then it's normal light again.

**Comment by Croydon** [comment]
Update: This explosion/light bug seems to happen only on Pandora.

**Comment by koraa** [comment]
Could you possibly add comments to the function you touched? I get that lmid+1 is an index into lightmaptexs…but WHY

**Comment by killme** [comment]
@Croydon that /should/ be fixed in 21d676e.

**Comment by koraa** [comment]
Cool. Now I am interested: How can it happen that the error is thrown multiple times?
Could we maybe approach this on the text/console level rather than directly in here?

As it seems to me from reading the code, this produces a lot of text. Maybe we can wait untill all or most errors have occurred and then print all the slots?

**Comment by koraa** [comment]
Btw, any particular reason for making the function and the variable static?

How about putting the set as a static varible inside the function, so It's scope is bound…

**Comment by killme** [comment]
No particular reason, was put outside of it so we can add a reset function in the future so it is reset on mapchange.

How do you mean the error can occur multiple times? There can be multiple invalid textures.

Not really sure if it would be a good idea to delay that as it is thrown on the first frame the texture is used, it's also not consistent with other error handling code currently in the engine.

**Comment by koraa** [comment]
Static in a global context means, that the variable is bound to the local translation unit (cpp file). That's why I am asking.

I mean, you are preventing that the error is is printed multiple times. So from what you said it sounds like that the error is thrown every time part of the texture is being rendered. Right?
Could we maybe save on the set by removing invalid textures from the texture list altogether? Possibly detecting invalid textures while they're being loaded?
That would render the code above a lot simpler and we would save on the set lookup every frame.

**Comment by killme** [comment]
We don't need it outside of it as of now, so that should be ok right?

The error is thrown every time the tmus are updated, so multiple times a frame, maps should be fixed to avoid this issue. I'm pretty sure it's not safe to remove textures at this point in the rendering pipeline. Throwing this at load time would be better but it is out of my current knowledge of the engine and seeing as this is the way error handling is done in other systems aswel, for example missing mapsounds, I don't think it's that much of an issue.

**Comment by Croydon** [comment]
@killme It is fixed. :)

**Comment by Croydon** [comment]
What about this?

**Comment by koraa** [comment]
I believe this can be merged, after the fixes have been squashed and the branch was rebased

**Comment by killme** [comment]
Better late than never ...
How about it now?

**Comment by a-teammate** [comment]
+1 go for it

**Pull request merged**
